spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://postgres:5432/instant-payment
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO

outbox:
  publisher:
    interval-ms: 3000
