server:
  port: 8080

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://postgres:5432/instant-payment
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
