spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/instant-payment
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true